=== FaLang

==== Prinzip

Ein Alternative zur Verwaltung mehrsprachiger Inhalte ist die
Joomla!-Erweiterung _FaLang_, die als Fork aus der Joomla 1.5
Erweiterung JoomFish entstanden ist. FaLang arbeitet nicht mit mehreren,
unabhängigen Seitenbäumen für die unterschiedlichen Sprachen sondern ist
eine Oberfläche zur 1:1 Übersetzung der Inhalte an zentraler Stelle.
Dabei werden ebenfalls über eine einheitliche GUI alle nur erdenklichen
Inhaltstypen übersetzt, jedoch ohne dass diese Übersetzungen in den
entsprechenden Joomla-Original-Listen auftauchen.

FaLang arbeitet somit gewissermaßen losgelöst von Joomla selbst, woraus
sich auch direkt der große Nachteil dieser Lösung ableiten lässt: wird
die Entwicklung FaLang irgendwann einmal eingestellt, sitzt man in der
Falle und muss die entsprechenden Inhalte umständlich per Hand in ein
anderes System bzw. die Core-Mehrsprachigkeitsfunktion übertragen. Der
große Vorteil von FaLang, nämlich das intuitive
1:1-Übersetzungsinterface ist durch die Sprachverknüpfungen von Joomla
3.7 größtenteils obsolet geworden, weshalb ich bei neuen Projekten davon
abraten würde, FaLang einzusetzen.
