=== Passwort-Manager

Als Webmaster, Entwickler und Designer kommen wir tagtäglich mit einer
Vielzahl an Zugangsdaten und Passwörtern in Berührung: FTP, MySQL,
Joomla!, der Kundenbereich des Webhosters und diverse Online-Dienste
seien hier beispielhaft aufgezählt.

Um dieser Flut Herr zu werden, gehen viele Nutzer dazu über, sich ein
einheitliches „Standardpasswort“ auszudenken und dieses dann mehrfach zu
verwenden. Im Bereich der IT-Sicherheit kann dieser Fall getrost als
Worst-Case-Szenario bezeichnet werden: Wird einer der Dienste, bei denen
sich der Benutzer angemeldet hat, erfolgreich gehackt, so hat der
Angreifer Zugriff auf das Klartext-Passwort und somit Zugang zu allen
weiteren Diensten.

Eine gern genutzte Alternative stellen Excel- oder Wordlisten auf dem
eigenen Rechner dar, in der alle, dann hoffentlich zufallsgenerierten
Passwörter, fein säublicher abgelegt ist. Der Nachteil dieses Ansatzes
ist jedoch, dass die Passwortliste unverschlüsselt ist und ein
Angreifer, z.B. über einen Trojaner, in den Besitz der kompletten Liste
kommen kann.

Ich möchte daher für jeden Internetnutzer allgemein, für Webmaster und
–designer und –entwickler aber ganz besonders, die Nutzung eines sog.
Passwort-Managers empfehlen. Die Funktionsweise ist dabei stets die
selbe: Nach der Installation des Passwort-Managers vergibt man ein
Master-Passwort, das den Zugriff auf die Passwörter regelt, die im
Manager gespeichert sind. Dieses Master-Passwort wird dabei gleichzeitig
dafür genutzt, die dort gespeicherten Passwörter mit einer sicheren
Verschlüsselungstechnologie zu verschlüsseln, sodass ein Angreifer
selbst mit Zugriff auf die Tresor-Datei keinen Zugriff auf die
Klartext-Passwörter erlangen kann.

Gängige Tools sind dabei die OpenSource-Lösung Keypass sowie die beiden
kommerziellen Anwendungen 1Password und Lastpass. Ich kann Ihnen an
dieser Stelle nur sehr nachdrücklich dazu raten, ein solches Tool
einzusetzen.
