==== JoomShopping

Eine Sonderrolle nimmt das Shop-System _JoomShopping_ ein. Die Software
eines deutschen Herstellers verfügt standardmäßig nur über einen
verhältnismäßig kleinen Funktionsumfang, der dann durch kostenpflichtige
Erweiterungen ergänzt werden kann. Dieses Grundprinzip gibt es zwar auch
bei anderen Systemen, JoomShopping verfolgt diesen Ansatz jedoch
besonders konsequent.

Die Erweiterung ist von Haus aus an einigen Stellen bereits für Shops im
deutschen Rechtsraum vorbereitet, was eine Besonderheit im
Joomla!-Shop-Umfeld darstellt, nichtsdestotrotz ist auch hier eine
rechtliche Prüfung unumgänglich.

[width="99%",cols="14%,86%",options="header",]
|===
|CHV++_++BOX++_++ID++_++02 |
|icn002 |Die Entwickler-Firma von JoomShopping ist in der Vergangenheit
durch eine etwas eigensinnige Auslegung der GPL-Lizenz aufgefallen und
verlangt zum Beispiel den Kauf einer Lizenz, um den Backlink im Shop
entfernen zu dürfen. Es gab hier in der Vergangenheit bereits daraus
resultierende Streitigkeiten mit Nutzern und dem Joomla-Projekt selbst,
weshalb Sie dies bei der Nutzung der Erweiterung berücksichtigen
sollten.
|===
