=== Shop-Systeme

Joomla! ist nach wie vor ein beliebtes System zur Realisierung von
Webshops, wobei das CMS dabei häufig in einem Atemzug mit der
Shop-Erweiterung _VirtueMart_ genannt wird. Dabei sollten Sie, bevor Sie
sich dazu entscheiden, ein CMS-System wie Joomla! durch eine
Shopping-Erweiterung zu ergänzen, grundsätzlich fragen, ob Sie sich
selbst und dem entsprechenden Projekt einen Gefallen damit tun.
Hintergrund dieser Überlegung ist, dass Shop-Erweiterungen in den
seltensten Fällen den Funktionsumfang und die Community-Größe eines
vollwertigen, Standalone-Systems wie Magento, Shopware oder Prestashop
erreichen und damit insbesondere bei komplexeren Anforderungen deutlich
früher an ihre Grenzen stoßen, als es spezialisierte
Standalone-Applikationen tun.

Somit ist die Grundfrage oftmals „habe ich eine Website mit einem
kleinen Shop oder einen großen Shop mit ein bisschen Website“ – bei
letzterem, wenn also der Shop-Anteil überwiegt, sind Standalone-Shops
oftmals die bessere Wahl.

Sind die Anforderungen jedoch überschaubar, kann auch ein Joomla-Shop
eine legitime Wahl sein. Im Folgenden möchte ich Ihnen einige der
Erweiterungen vorstellen.

[width="99%",cols="14%,86%",options="header",]
|===
|CHV++_++BOX++_++ID++_++01 |
|icn001 |Da die Joomla-Shopping-Erweiterungen für die internationalen
Markt entwickelt werden, sind landesspezifische „Spezialitäten“
insbesondere im rechtlichen Bereich in den meisten Fällen nicht
berücksichtigt, eine professionelle Prüfung auf die Einhaltung der
rechtlichen Vorgaben ist daher insbesondere im komplexen deutschen
E-Commerce Recht unumgänglich.
|===

include::01-01-virtuemart.adoc[]

include::01-02-hika.adoc[]

include::01-03-j2store.adoc[]

include::01-04-joomshopping.adoc[]
