=== Formulare

Eine häufige Aufgabenstellung im professionellen Umfeld ist das Anlegen
spezieller Formulare, die vom Benutzer ausgefüllt und abgesendet werden
können. Denken Sie beispielsweise an individuelle Kontaktformulare,
speziell angepasste Formulare für Supportanfragen oder ein Formular zur
Bewerbung auf ein Stellenangebot. Um diese Formulare flexibel anlegen
und verwalten zu können, bieten zahlreiche Hersteller entsprechende
Tools an.

Eine Besonderheit im Bereich der Formulare ist, dass viele populäre,
kostenfreie Erweiterungen wie BreezingForms oder Proforms schon seit
Jahren auf dem Markt sind und dabei häufig aus Vorgängererweiterungen
weiterentwickelt wurden – leider sind diese Erweiterungen dabei „unter
der Haube“ auch nie grundlegend erneuert worden, weshalb sich dort
teilweise haarsträubende Altlasten verbergen, die weit von einer
modernen, systemnahen Umsetzung entfernt sind. Daher sollten Sie
insbesondere in diesem Erweiterungssegment einen genauen Blick in den
Code der jeweiligen Erweiterung werfen.

include::02-01-rsforms.adoc[]

include::02-02-flexforms.adoc[]
