=== Taskrunner

Um Projekte effizient und mit wenig Code zu verwirklichen, wiederholen
wir häufig gewisse Arbeitsschritte. Wir optimieren Bildmaterial,
kompilieren LESS oder SASS in minimierte CSS-Dateien. Das kostet viel
Zeit und ist ineffizient.

Taskrunner[.indexref]#### nehmen uns diese wiederkehrenden Prozesse ab,
indem sie die von uns vorgegebenen Arbeitsschritte abarbeiten. Unter
anderem können das sein:

[arabic]
. CSS

* SASS oder LESS in CSS kompilieren.
* Autoprefixer im CSS anwenden, um eventuelle Browserpräfixe zu
ergänzen.
* Komprimierung der CSS-Dateien.

[arabic, start=35]
. Javascript

* Javascript-Fehler identifizieren.
* Scripte zu einer Datei zusammenfassen.
* Komprimierung der Skripte.

[arabic, start=36]
. Bilddaten

* Bildmaterial optimieren und die Dateigröße verringern.

Taskrunner bieten die Möglichkeit, Dateiänderungen zu beobachten und
Aufgaben auszuführen, sobald Sie notwendig sind. Über Browsersync kann
man seine Entwicklung auf mehreren Browsern und Endgeräten gleichzeitig
testen, ohne die Seite neu laden zu müssen.

Die zwei bekanntesten Taskrunner sind zum Beispiel Gulp und Grunt.

Für weitere Informationen zu den Taskrunnern empfehle ich Ihnen einen
Einstieg in die jeweilige Projekt-Dokumentation.

* Grunt: https://gruntjs.com/[[.underline]#https://gruntjs.com/#]
* Gulp: https://gulpjs.com/[[.underline]#https://gulpjs.com/#]
* Broccoli: http://broccolijs.com/
* Cake: http://cakebuild.net/
