=== Erweiterungen

Neben diesen integrierten Funktionen bieten externe Anbieter eine Unzahl
an Erweiterungen für die Suchmaschinenoptimierung von
Joomla!-Installationen.

==== sh404SEF

_sh404SEF_ (https://weeblr.com/) ist die wohl umfangreichste
SEO-Erweiterung für Joomla!, die derzeit verfügbar ist, und bietet eine
riesige Anzahl von Features:

* Generierung von suchmaschinenfreundlichen URLs – ersetzt den
Joomla!-internen Algorithmus und erlaubt so die manuelle Anpassung von
URLs
* Unterstützung von zahlreichen externen Komponenten
* Vermeidet seiteninternen _Duplicate Content_, indem verschiedene
interne URLs, die auf den gleichen Inhalt verlinken, die gleiche
suchmaschinenfreundliche URL erhalten
* Generierung eigener 404-Seiten
* Weiterleitung von fehlerhaften auf korrekte URLs
* Pflege von zahlreichen Meta-Daten und Robot-Einstellungen
* Integrierte Auswertungsmöglichkeiten mit Google Analytics

Die Erweiterung ist also unheimlich mächtig und verfügt über zahlreiche
Features, hat jedoch in vielen Fällen die nervige Angewohnheit,
fehlerhafte URLs zu erzeugen, die dann manuell gelöscht werden müssen.
Zudem ist sie nur in einem kostenpflichtigen Abonnement erhältlich.
Dennoch ist _sh404SEF_ meine klare Empfehlung, wenn man denn wirklich
volle Kontrolle über die URLs benötigt.

==== OSMap

Mit der Erweiterung _OSMap_ ist es möglich, sog. XML-Sitemaps zu
erstellen, die anschließend von Suchmaschinen ausgelesen werden können.
Mehr Informationen hierzu finden Sie in Kapitel 18.1.1, „OSMap“.

==== Easy Frontend SEO

Die Erweiterung _EFSEO – Easy Frontend SEO_
(https://joomla-extensions.kubik-rubik.de/) erlaubt die bequeme
Verwaltung von _Meta-Daten_ direkt aus dem Frontend heraus und ist somit
ein interessantes Werkzeug wenn man mit speziellen Dienstleistern für
die Optimierung zusammenarbeitet, denen man im Frontend eine einfache
und schnelle Möglichkeit zur Bearbeitung geben möchte. Darüber hinaus
verfügt die Erweiterung über einen Automatik-Modus der die
entsprechenden Daten automatisch aus dem entsprechenden Inhalt generiert
– naturgemäß ist die Qualität dieser Automatik aber natürlich
beschränkt.
