=== Online-Checkliste

Ist die Seite schließlich online, so gibt es stets einige festgelegte
Schritte, die ich ausführe, um sicherzustellen, dass die Installation
auch wirklich fertig für den produktiven Betrieb ist. Diese Checkliste
möchte ich Ihnen nicht vorenthalten.

[width="100%",cols="12%,37%,51%",]
|===
|Schritt |Titel |Beschreibung

|1 |XML-Sitemap prüfen (siehe Kapitel 18.1.1) |Prüfen, ob die
suchmaschinenfreundlichen URLs korrekt funktionieren und der Aufruf von
_domain.tld/sitemap.xml_ zur XML-Sitemap führt

|2 |XML-Sitemap bei Google eintragen |Eintragung der XML-Sitemap in den
Google Webmaster-Tools zur schnelleren Indexierung der neuen Seite

|3 |Meta-Tags und Meta-Description prüfen |Wurden die Standardeinträge
von Joomla! durch aussagekräftige Angaben ersetzt? Ist der robots-Tag
korrekt gesetzt?

|4 |Mailserver-Angaben prüfen |Werden Systemmails, z.B. bei der
Registrierung eines neuen Benutzers, erfolgreich versendet?

|5 |System und Erweiterungen auf Aktualität prüfen |Gibt es eventuell
bereits neuere Versionen für Joomla! und die verwendeten
Drittkomponenten? Falls ja, sollten diese unbedingt eingespielt werden!

|6 |Versionen dokumentieren |Verwendete Erweiterungen und deren
Versionen sowie die verwendete Joomla!-Version in einer zentralen Datei
dokumentieren, um bei Updates auf einen Blick sehen zu können, welche
Seiten aktualisiert werden müssen

|7 |Backup erstellen |Backup der fertigen Seite erstellen und auf dem
lokalen Rechner sichern, um stets zur Ausgangvariante zurückkehren zu
können
|===

Diese Liste lässt sich natürlich beliebig fortführen, sollte jedoch die
wichtigsten Schritte abdecken und hat mir schon oft Zusatzarbeit und
peinliche Gespräche mit Kunden erspart.
