[[17-erweiterungen-erstellen]]

== Eigene Erweiterungen

Die Entwicklung eigener Erweiterungen stellt gewissermaßen die
Königsdisziplin in der Webentwicklung mit Joomla! dar. Das Programmieren
setzt gute _MySQL-_, _PHP-_, _HTML-_ und _PHP_-Kenntnisse sowie gute
Kenntnisse der Eigenheiten der Joomla!-_API_ voraus und kostet deshalb
unter Umständen sehr viel Zeit und Nerven. Auf der anderen Seite ist es
schwer, komplexere Anwendungen mit Joomla! umzusetzen, ohne das System
mit individuell programmierten Erweiterungen anzupassen.

Ich möchte Ihnen nichts vormachen: Ohne Kenntnisse in den genannten
Sprachen wird dieses Kapitel für Sie vermutlich relativ schwer
verständlich sein. Ich möchte Sie aber dennoch ermutigen. Beißen Sie
sich durch, denn durch das Lesen des Codes können Sie auch ohne
Programmierkenntnisse die grundlegenden Zusammenhänge der _API_
begreifen und dadurch etwaige Modifikationen an bestehenden
Erweiterungen leichter durchführen.

include::abschnitte/01-joomla-api.adoc[]

include::abschnitte/02-mvc-pattern.adoc[]

include::abschnitte/03-wichtige-klassen.adoc[]

include::abschnitte/04-tutorial-komponente-entwickeln.adoc[]

include::abschnitte/05-cli-app-entwickeln.adoc[]

include::abschnitte/06-fof.adoc[]
