=== Die Joomla-API

Als Joomla!-_API_ bezeichnet man eine Sammlung verschiedener Klassen und
Methoden in Joomla!, die häufig auftretende Aufgaben in der
Programmierung bereits lösen und von Erweiterungsentwicklern verwendet
werden können. Beispielsweise muss ein Entwickler, der in seiner
Erweiterung eine Mail verschicken möchte, nicht auf die standardmäßig
integrierte mail()-Funktion von PHP zurückgreifen, sondern kann
stattdessen die Klasse JMail verwenden, die automatisch die
Mailzugangsdaten in der Joomla!-Konfiguration verwendet. Die _API_ ist
also gewissermaßen ein Grundgerüst, auf das wir als Entwickler beim
Programmieren eigener Erweiterungen zurückgreifen können, um uns Arbeit
zu ersparen.

Die Joomla!-API hat seine Wurzeln in der Joomla!-Version 1.5 und setzt
in hohem Maße auf das auch aus anderen Frameworks (Zend, Symfony, Cake,
Ruby on Rails) bekannte Pattern _Model View Controller_ (kurz _MVC_).

[width="99%",cols="14%,86%",options="header",]
|===
|CHV++_++BOX++_++ID++_++02 |
|icn002 |Das Joomla-Projekt hat einige Klassen der API in ein separates
und unabhängig vom CMS verwendbares Framework ausgelagert, das derzeit
unter dem Namen _Joomla Framework_ entwickelt wird. Dieses separate
Projekt wurde dabei früher unter dem Namen _Joomla Plattform_ betrieben
und erst später umbenannt. Leider verwenden einige Online- wie
Offline-Quellen die Begriffe _API_, _Framework_ und _Plattform_ nicht
korrekt, sondern vermischen die losgelösten Projekte miteinander, somit
sollten Sie bei entsprechenden Quellen immer prüfen, auf welches Projekt
sich diese beziehen.
|===
