=== Wichtige Klassen

Bevor wir nun mit der Programmierung unserer Beispielkomponenten
loslegen, lohnt es sich, einen kleinen Überblick über die verschiedenen
Klassen der _API_ und die damit verbundenen Möglichkeiten zu gewinnen.
Neben den wichtigsten Klassen finden Sie auch eine kurze Beschreibung
der am häufigsten genutzten und zur Verfügung stehenden Methoden.

[width="99%",cols="14%,86%",options="header",]
|===
|CHV++_++BOX++_++ID++_++04 |
|icn004 |Eine automatisch generierte API-Dokumentation mit allen Klassen
und Methoden der API finden Sie in der Joomla! API-Dokumentation unter
[.underline]#https://api.joomla.org/cms-3/index.html#.
|===

[width="99%",cols="14%,86%",options="header",]
|===
|CHV++_++BOX++_++ID++_++02 |
|icn002 |*Hinweis:* In den folgenden Auflistungen der wichtigsten
Methoden finden Sie ausschließlich die jeweiligen Pflichtparameter der
Methode – die optionalen Parameter entnehmen Sie bitte der vollständigen
API-Beschreibung unter [.underline]#api.joomla.org#.
|===

==== JFactory

Die Klasse JFactory implementiert das sogenannte _Factory_-Pattern in
der Joomla!-_API_. Dieses Pattern soll dafür sorgen, dass von bestimmten
Objekten jeweils nur eine Instanz existiert, und dadurch die Nutzung
dieser Objekte vereinfachen und zugleich Arbeitsspeicher einsparen.

Ein Beispiel gefällig? Wenn Sie mit Ihrer Erweiterung eine Mail
versenden wollen, bietet Ihnen die _API_ dazu die Klasse JMail an. Ohne
JFactory würde der entsprechende Code wie in Listing 17.1 aussehen.

LISTING 17.1 Direkter Aufruf der JMail-Klasse mittels Konstruktor

$mail = new JMail();

$mail-++>++addRecipient("test@example.com");

$mail-++>++setSubject("Testmail");

$mail-++>++send();

Bei der Nutzung des _Factory_-Patterns nutzen wir, wie in Listing 17.2
abgebildet, anstelle des direkten Aufrufs des Konstruktors die
entsprechende Methode der _Factory_.

LISTING 17.2 Erzeugung der Instanz über die Nutzung der Factory-Methode

$mail = JFactory::getMailer();

$mail-++>++addRecipient("test@example.com");

$mail-++>++setSubject("Testmail");

$mail-++>++send();

TABELLE 17.1 Wichtige Methoden der JFactory-Klasse

[width="100%",cols="42%,58%",]
|===
|Methode |Beschreibung

|JFactory::getMailer(); |Erzeugt eine Instanz des JMail-Objekts zum
Versand von E-Mails

|JFactory::getDBO(); |Erzeugt eine Instanz des JDatabase-Objekts zur
Ausführung von Datenbankabfragen

| |

|JFactory::getConfig(); |Erzeugt eine Instanz des JConfig-Objekts, das
die Werte der configuration.php aus dem Joomla!-Hauptverzeichnis enthält

|JFactory::getDocument(); |Erzeugt eine Instanz des jeweiligen
JDocument-Objekts (JDocumentHTML, JDocumentFeed), das uns erlaubt, das
ausgegebene Dokument zu manipulieren

|JFactory::getUser(); |Gibt das JUser-Objekt zurück, das zum derzeit
angemeldeten Benutzer gehört

|JFactory::getLanguage(); |Erzeugt eine Instanz des JLanguage-Objekts
zur Abfrage der aktuellen Sprachversion

|JFactory::getDate(); |Erzeugt eine Instanz des JDate-Objekts zur
Datumsverarbeitung und -ausgabe

|JFactory::getApplication(); |Erzeugt eine Instanz des aktuellen
JApplication-Objekts
|===

==== JDatabase

Die Klasse JDatabase übernimmt mit ihren diversen Treibern für
unterschiedliche Datenbanken die direkte Kommunikation mit der
verwendeten Datenbank und stellt uns dabei einheitliche Methoden zur
Verfügung, die wir in unserer Erweiterung nutzen können. Zugleich
ersetzt die Klasse automatisch den Platzhalter #++__++ in unseren
Datenbankabfragen durch das Datenbank-Präfix der jeweiligen
Joomla!-Installation.

LISTING 17.3 Beispiel für die Nutzung der Klasse JDatabase

$db = JFactory::getDBO();

$query = "SELECT email FROM #++__++users WHERE username = 'admin'";

$db-++>++setQuery($query);

$email = $db-++>++loadResult();

TABELLE 17.2 Wichtige Methoden der JDatabase-Klasse

[width="100%",cols="32%,68%",]
|===
|Methode |Beschreibung

| |

|loadObject(); |Lädt eine einzelne Zeile als Ergebnis einer vorher
definierten SQL-Abfrage aus der Datenbank

|loadObjectList(); |Lädt mehrere Zeilen als Ergebnis einer zuvor
definierten SQL-Abfrage

|loadResult(); |Lädt den Inhalt einer einzelnen Zeile und Spalte
(sozusagen ein „Feld“) aus der Datenbank aufgrund einer zuvor
definierten SQL-Abfrage

|quote($string); |Versieht einen übergebenen String mit korrekten
Anführungszeichen (Quotes) und escaped den Inhalt zur sicheren
Verwendung in der Datenbankabfrage

|quoteName($string); |Versieht den übergebenen String mit korrekten
Anführungs­zeichen zur Verwendung als Spaltenname in einer
Datenbankabfrage

|insertid(); |Gibt die ID des letzten, per auto++_++increment
hinzugefügten ­Eintrags zurück

|execute(); |Führt die vorher per setQuery gesetzte SQL-Abfrage aus

|setQuery($query); |Übergibt eine auszuführende, per JDatabaseQuery
definierte SQL-Abfrage an JDatabase

| |
|===

==== JDatabaseQuery

Die Klasse JDatabaseQuery übernimmt über diverse Treiber die Generierung
der Datenbankabfragen, die an die jeweils verwendete Datenbanksoftware
angepasst werden müssen. Daher sollten Sie, wie in Listing 17.4
abgebildet, niemals manuell Datenbankabfragen an der „API vorbei“
definieren.

LISTING 17.4 Beispiel für die Nutzung von JDatabaseQuery

$db = JFactory::getDBO();

$query = $db-++>++getQuery(true);

$query-++>++select("email, username");

$query-++>++from("#++__++users");

$db-++>++setQuery((string)$query);

$users = $db-++>++loadObjectList();

foreach($users as $user) ++{++

echo '++<++a
href="'.$user-++>++email.'"++>++'.$user-++>++username.'++<++/a++>++';

}

TABELLE 17.3 Wichtige Methoden der Klasse JDatabaseQuery

[width="100%",cols="38%,62%",]
|===
|Methode |Beschreibung

|delete($tabelle) |Erzeugt ein DELETE FROM-Statement

|from($tabelle) |Erzeugt ein FROM-Statement

|group($spalten) |Erzeugt ein GROUP BY-Statement

|insert($tabelle) |Erzeugt ein INSERT INTO-Statement

|join($typ,$bedingung) |Erzeugt ein JOIN-Statement

|order($spalten) |Erzeugt ein ORDER BY-Statement

|select($spalten) |Erzeugt ein SELECT-Statement

|update($tabellen) |Erzeugt ein UPDATE-Statement

|where($bedingung, $glue) |Erzeugt ein WHERE-Statement, wobei die
Variable $glue definiert, welchem Vergleichsoperator (AND, OR etc.) das
Statement verkettet werden soll

|set($condition) |Erzeugt ein SET-Statement
|===

==== JInput

Die Klasse JInput dient zur Abfrage und Manipulation der ursprünglichen
Nutzerabfrage – insbesondere zur Abfrage der Werte, die mittels URL
(_index.php?schluessel=wert_) oder Formular an die Seite übergeben
werden. Der „normale“ Weg für diese Aufgabe wäre die Abfrage der
globalen Arrays $++_++GET, $++_++POST und $++_++REQUEST, die API
hingegen sieht dafür die Methode get() der JInput-Klasse vor, die dabei,
je nach Filter (3. Parameter), bereits eine Bereinigung der Eingaben
vornimmt.

Der große Vorteil dieses im ersten Moment umständlich wirkenden
Verfahrens ist die Tatsache, dass die JInput-Klasse über verschiedene
Adapter auch dafür verwendet werden kann, andere Eingabeformate
(JSON-Objekt, Kommandozeilen-Parameter beim Aufruf via Shell) zu parsen
und dann über die einheitliche Methode get() zur Verfügung zu stellen.
Dadurch ist es nicht mehr nötig, Anpassungen an der eigenen Anwendung
vorzunehmen, wenn das System in einer anderen Umgebung (Webservice, CLI)
ausgeführt wird.

Die get()-Methode verfügt über drei Parameter:

* Der erste Parameter dient zur Angabe des Variablennamens.
* Der zweite Parameter definiert einen Defaultwert, der zurückgegeben
wird, wenn die entsprechende Variable nicht gesetzt ist.
* Der dritte Parameter dient zur Auswahl des anzuwendenden
Eingabefilters (siehe Tabelle 17.4).

LISTING 17.5 Beispiel für die Nutzung der JInput-Klasse

//Abfrage des Parameters id aus dem $++_++REQUEST Array

$input = JFactory::getApplication()-++>++input;

$id = $input-++>++get('id','0','INT');

//Abfrage des Parameters name aus dem $++_++POST Array

$input = JFactory::getApplication()-++>++input;

$name = $input-++>++post-++>++get('name','','STRING');

TABELLE 17.4 Filter der JInput Klasse

[width="100%",cols="16%,84%",]
|===
|Filter |Beschreibung

|INT |Gibt nur ganzzahlige Werte zurück

|INTEGER |Siehe INT

|UINT |Gibt nur positive ganzzahlige Werte zurück

|FLOAT |Gibt nur Fließkommazahlen zurück

|DOUBLE |Siehe FLOAT

|BOOL |Gibt nur boolesche Werte (TRUE, FALSE) zurück

|BOOLEAN |Siehe BOOL

|WORD |Gibt nur einzelne Wörter (Buchstaben A– Z) zurück

|ALNUM |Gibt nur alphanumerische Strings (Buchstaben A– Z, Zahlen)
zurück

|CMD |Gibt nur Strings zurück, die aus Buchstaben (A– Z), Zahlen,
Punkten und Minuszeichen bestehen

|BASE64 |Gibt nur gültige mit base64 encodierte Strings zurück

|STRING |Gibt nur Strings (ohne HTML) zurück

|HTML |Gibt von möglicherweise schädlichen Tags befreiten HTML-Code
zurück

|ARRAY |Führt keine Filterung durch, sondern gibt ein ungefiltertes
Array zurück

|PATH |Stellt sicher, dass es sich bei dem String um eine gültige
Pfadangabe handelt

|TRIM |Entfernt Leerzeichen am Beginn und Ende des Eingabestrings

|USERNAME |Entfernt alle Zeichen, die nicht in einem Benutzernamen
verwendet werden ­können

|RAW |Gibt die rohen Eingabedaten ohne Filterung zurück
|===

==== JDocument

JDocument ist die in Joomla! integrierte Klasse zur Generierung eines
Dokuments, das an die API zur Ausgabe an den Benutzer übergeben wird.
Joomla! unterstützt bereits von Haus aus verschiedene Dokumententypen,
die dann wiederum über einige individuelle Methoden angepasst werden
können:

* RSS- bzw. Atom-Feed
* HTML
* JSON
* XML
* OpenSearch XML-Dokument
* Raw (reine Ausgabe der Komponente)

Der jeweilige Dokumententyp kann über die Angabe des Parameters
_format=DOKUMEN­TENTYP_ in der jeweiligen URL gewählt werden, wobei zu
beachten ist, dass die entsprechende Komponente den gewählten Ausgabetyp
unterstützen muss.

Da eine Joomla!-Erweiterung in der Regel HTML-Code ausgeben wird, möchte
ich mich in meinem Beispiel und in der Methodenübersicht auf die dazu
passende Klasse JDocumentHTML beschränken.

LISTING 17.6 Beispiel zur Nutzung von JDocumentHTML

$document = JFactory::getDocument();

$document-++>++addStyleSheet("/media/com++_++jobs/jobs.css");

$document-++>++setGenerator("Joomla 7.0");

TABELLE 17.5 Wichtige Methoden der Klasse JDocumentHTML

[width="100%",cols="44%,56%",]
|===
|Methode |Beschreibung

|addScript($url) |Fügt eine Verlinkung zum unter $url abgelegten
JS-Dokument zum Head der Seite hinzu

|addStyleSheet($url) |Fügt eine Verlinkung zum unter $url abgelegten
CSS-Dokument zum Head der Seite hinzu

|addHeadLink($href, $relation) |Fügt einen ++<++link++>++-Tag zum Head
der Seite hinzu

|getTitle() |Gibt den Titel des Dokuments zurück

|setTitle($title) |Setzt den Titel des Dokuments

|setLanguage($language) |Setzt die Sprache des Dokuments

|getLanguage() |Gibt die Sprache des Dokuments zurück

|setDescription($description) |Setzt die Beschreibung des Dokuments

|getDescription() |Gibt die Beschreibung des Dokuments zurück
|===

==== JFile/JFolder

Die Klassen JFile und JFolder dienen zur Interaktion mit dem Dateisystem
der Seite. Joomla! greift dafür auf eigene Klassen zurück, um dem
Entwickler einen leichten Zugriff auf die Ordner und Dateien der
Installation zu erlauben, ohne dass dieser sich um die zwei
verschiedenen Zugriffsarten (direkter Dateizugriff mit den PHP-eigenen
Dateioperationen oder Nutzung des in Joomla! integrierten FTP-Modus)
kümmern muss.

LISTING 17.7 Beispiel zur Nutzung der Klassen JFile und JFolder

jimport('joomla.filesystem.file');

jimport('joomla.filesystem.folder');

$path = JPATH++_++SITE."/images/";

if(JFolder::exists($path))

++{++

$files = JFolder::files($path);

foreach ($files as $file)

++{++

echo "Datei: ".$file." ++|++ Dateityp: ".JFile::getExt($file);

}

}

Tabelle 17.6 Wichtige Methoden von JFile und JFolder

[width="100%",cols="37%,63%",]
|===
|Methode |Beschreibung

|JFile |

|copy($quelle, $ziel) |Kopiert die Datei $quelle nach $ziel

|delete($datei) |Löscht die Datei $datei

|exists($datei) |Prüft, ob die Datei $datei existiert

|getExt($datei) |Gibt die Dateierweiterung (.jpg, .html etc.) der
jeweiligen Datei zurück

|makeSafe($datei) |Bereinigt den übergebenen String um alle Zeichen, die
zu Problemen mit dem Dateisystem führen könnten (Sonderzeichen, Umlaute
etc.)

|move($quelle, $ziel) |Verschiebt die Datei $quelle nach $ziel

|read($datei) |Veraltet, file++_++get++_++contents verwenden

|upload($quelle, $ziel) |Verschiebt die ins temporäre Verzeichnis der
PHP-Installation hochgeladene Datei $quelle an die Stelle $ziel

|write($datei, $inhalt) |Schreibt den übergebenen Inhalt $inhalt in die
jeweilige Datei $datei

|JFolder |

|copy($quelle, $ziel) |Kopiert den Ordner $quelle inklusive Inhalte nach
$ziel

|create($ordner) |Erstellt den Ordner $ordner

|delete($ordner) |Löscht den Ordner $ordner

|exists($ordner) |Prüft, ob der Ordner $ordner existiert

|Files($ordner) |Gibt ein Array der in $ordner enthaltenen Dateien
zurück

|folders($ordner) |Gibt ein Array der in $ordner enthaltenen Ordner
zurück

|listFolderTree($ordner, $filter, $tiefe) |Gibt ein mehrdimensionales
Array der in $ordner enthaltenen Ordner bis zu einer gewissen $tiefe
zurück

|makeSafe($ordner) |Bereinigt den übergebenen String um Zeichen
(Umlaute, Sonderzeichen etc.), die in einem Ordnernamen zu Problemen
führen könnten

|move($quelle, $ziel) |Verschiebt einen Ordner $quelle nach $ziel
|===

==== JControllerLegacy

Die Klasse JControllerLegacy dient bereits seit Jahren als
Basisimplementierung des _Controllers_ im bereits erwähnten
_MVC_-Pattern. Der _Controller_ verarbeitet die Anfrage des Nutzers und
führt, basierend auf dieser Anfrage, weitere Aktionen aus. Da die
Implementierung bereits etwas in die Jahre gekommen ist, gab es eine
Initiative die damals noch als JController benannte Klasse durch einen
moderneren Nachfolger zu ersetzen, weshalb die Klasse zu
JControllerLegacy umbenannt wurde. Fakt ist jedoch, dass sich die „neue“
Implementierung nie durchgesetzt hat, weshalb JControllerLegacy bis
heute der De-Factor-Standard in der API ist. Die API bringt dafür als
Besonderheit bereits zwei zusätzliche Implementierungen mit, die gängige
Anwendungsfälle in der Programmierung abdecken und dadurch zur
Reduzierung von Code-Dopplungen beitragen. Diese Controller heißen
JControllerAdmin und JControllerForm.

===== JControllerAdmin

Die Klasse JControllerAdmin implementiert erweiterungsunabhängige
Funktionen zum Bearbeiten und Anzeigen von Listenansichten im Backend:

* Veröffentlichen
* Sperren
* Archivieren
* Verschieben in den Papierkorb
* Verändern der Eintragsreihenfolge
* Löschen
* Anzeigen der Liste

===== JControllerForm

Die Klasse JControllerForm implementiert Funktionen, die zum Editieren
eines einzelnen Eintrags in einer Formularansicht notwendig sind:

* Anzeigen des Formulars
* Hinzufügen eines Inhalts
* Editieren eines Inhalts
* Validierung der Eingaben

==== JModelLegacy

Die Klasse JModelLegacy implementiert ein rudimentäres Model für das
Joomla!-eigene _MVC_-Pattern. Wie bei JControllerLegacy gilt auch hier,
dass die schon relativ alte Implementierung durch eine moderne Klasse
mit einem anderen Ansatz ersetzt werden sollte, sich dieser Versuch aber
nicht durchgesetzt hat. Zudem gibt es auch hier bereits Unterklassen,
die für spezifische Anwendungsfälle optimiert sind:

===== JModelAdmin

JModelAdmin implementiert alle administrativen Funktionen, die im
Regelfall im Model notwendig sind:

* Verschieben
* Löschen
* Zuweisen der Sprache
* Abrufen von Inhalten
* Reihenfolge verändern
* Speichern

===== JModelForm

JModelForm implementiert die Funktionen zur Generierung und Validierung
der verwendeten Formulare mittels JForm.

==== JViewLegacy

Die Klasse JViewLegacy implementiert die View der MVC-Triade. Dabei ist
es möglich, basierend auf JViewLegacy verschiedene Views zu definieren,
um unterschiedliche Ausgabemedien (HTML, CSV, JSON) bedienen zu können.
Die Klasse unterstützt zudem die Nutzung von Templates, um Logik und
Ausgabe voneinander trennen zu können. Die Anmerkungen zum Legacy Suffix
können dabei ebenfalls von JContollerLegacy übernommen werden.

==== JForm

Die Klasse JForm dient zur Generierung und Validierung von
Eingabeformularen jeglicher Art, wobei das jeweilige Formular in einem
XML-Dokument abgelegt und dann durch die Klasse geparst wird. Dabei
stehen bereits von Haus aus verschiedene Feldtypen sowie
Filtermöglichkeiten zur Verfügung, wodurch es sehr leicht wird, binnen
kürzester Zeit eigene Formulare generieren zu lassen.

Eine Besonderheit von JForm ist, dass es durch die geschickte Verwendung
von Plug-ins möglich wird, jedes bestehende Formular der
Joomla!-Installation zu modifizieren, ohne dabei in den Code der
ursprünglichen Komponente eingreifen zu müssen.footnote:[Voraussetzung
für die Modifikation ist, dass das entsprechende Formular mittels JForm
generiert wird und die entsprechende Erweiterung auf JModelForm bzw.
JModelAdmin zurückgreift.]

===== Verfügbare Feldtypen

TABELLE 17.7 Standardmäßig verfügbare Feldtypen der Klasse JForm

[width="100%",cols="28%,72%",]
|===
|Feldtyp |Beschreibung

|_Author_ |Select-Liste der Nutzer, die als Autor eines Beitrags
hinterlegt sind

|_Accesslevel_ |Select-Liste der verfügbaren Zugriffsebenen

|_Aliastag_ |Select-Liste der verfügbaren Schlagwort-Typen

|_Cachehandler_ |Select-Liste der verfügbaren Caching-Methoden (Datei,
memcache, xcache etc.) – siehe Kapitel 20.1.3, „Integriertes Joomla!
Caching“

|_Calendar_ |Einzeiliges Textfeld mit JavaScript-Widget zur Auswahl
eines Datums

|_Category_ |Select-Liste der verfügbaren Kategorien

|_Captcha_ |Gibt ein Captcha auf Basis der Joomla-Captcha-Plugins aus

|_Checkbox_ |Stellt eine einzelne Checkbox für simple Ja-/Nein-Abfragen
dar

|_Checkboxes_ |Gibt mehrere Checkboxen zur Auswahl des gewünschten Werts
aus

|_Chromestyle_ |Select-Liste der verfügbaren Modul-Chromes

|_Color_ |Einzeiliges Eingabefeld mit auf JavaScript basierendem
Color-Picker

|_Combo_ |Freitextfeld, bei dem Werte entweder manuell eingegeben oder
aus einer Dropdown-Liste ausgewählt werden können.

|_Components_ |Select-Liste der verfügbaren Komponenten

|_Componentlayout_ |Select-Liste der verfügbaren Layouts einer
Komponente

|_Contentlanguage_ |Select-Liste der verfügbaren Sprachen zur
Inhaltsübersetzung

|_Contenttype_ |Select-Liste der verfügbaren Inhaltstypen

|_Contenthistory_ |Generiert einen Button zur Betrachtung der
Inhaltsversionen eines bestimmten Inhalts

|_Databaseconnection_ |Select-Liste der verfügbaren Datenbanktreiber
(MySQL, MySQLi, Azure etc.)

|_Editor_ |Textarea mit WYSIWYG-Editor

| |

|_Email_ |Textfeld zur Eingabe einer E-Mail-Adresse

|_File_ |Erzeugt ein Eingabefeld zum Hochladen einer Datei

|_Filelist_ |Erzeugt eine Select-Liste der Dateien eines bestimmten
Verzeichnisses

|_Folderlist_ |Erzeugt eine Select-Liste der Ordner eines bestimmten
Verzeichnisses

|_Frontend++_++language_ |Select-Liste der veröffentlichten
Sprachversionen im Frontend

|_Groupedlist_ a|
Erzeugt eine Select-Liste mit gruppierten Einträgen.

Beispiel: Wählen Sie Ihr Bundesland:

* Deutschland
* NRW
* Hessen
* Bayern
* usw.
* Österreich
* Tirol
* usw.

|_Headertag_ |Select-Liste für HTML-Überschriftst-Tags

|_Helpsite_ |Erzeugt eine Select-Liste der verfügbaren Hilfe-Server für
den Abruf der in Joomla! integrierten Hilfe-Funktion

|_Hidden_ |Verstecktes Feld

|_Imagelist_ |Erzeugt eine Select-Liste der Bilder in einem bestimmten
Verzeichnis

|_Integer_ |Erzeugt eine Select-Liste mit ganzzahligen Werten, deren
Ober- und Untergrenze zu definieren ist

|_Lastvisitdaterange_ |Select-Liste mit vordefinierten Datumsbereichen
(heute, letzte Woche, letzter Monat etc.)

|_Language_ |Erzeugt eine Select-Liste der in Joomla! installierten
Sprachdateien

|_List_ |Erzeugt eine Select-Liste

|_Media_ |Erzeugt einen Button zur Auswahl einer Datei aus dem
Medien-Manager mittels Popup

|_Meter_ |Eingabeelement zur Auswahl eines Werts auf einer vorgegeben
Skala

|_Menu_ |Erzeugt eine Select-Liste der verfügbaren Menüs

|_Menuitem_ |Erzeugt eine Select-Liste der verfügbaren Menüeinträge

|_Modulelayout_ |Erzeugt eine Select-Liste der Layouts eines bestimmten
Moduls

|_Moduleorder_ |Bedienelement zur Veränderung der Reihenfolge eines
Moduls auf einer bestimmten Modulposition

|_Moduleposition_ |Select-Liste der Modulpositionen

|_Moduletag_ |Erzeugt eine Select-Liste von HTML-Elementen, die als
umgebender Tag für Module verwendet werden können

|_Note_ |Gibt anstelle eines Eingabefelds einen Beschreibungstext aus,
der zur besseren Gliederung des Formulars genutzt werden kann

|_Number_ |Erzeugt ein HTML5-Number Feld zur Eingabe eines ganzzahligen
Werts

|_Ordering_ |Erzeugt ein Bedienelement zur Anpassung der Reihenfolge

|_Password_ |Erzeugt ein Eingabefeld zur Eingabe eines Passworts

|_Plugins_ |Erzeugt eines Select-Liste der verfügbaren Plug-ins

|_Plugin++_++status_ |Erzeugt eine Select-Liste mit den beiden Status
_Veröffentlicht_ und _Gesperrt_

|_Predefinedlist_ |Erweiterung des _List_ Typs, erlaubt die Filterung
und Übersetzung der Listen-Werte

|_Radio_ |Erzeugt Radiobuttons zur Auswahl eines Werts

|_Range_ |Siehe _Meter_

|_Registrationdaterange_ |Siehe _Lastvisitdaterange_

|_Repeatable_ |Erzeugt einen Feldtyp, bei dem ein Eingabefeld auf
Knopfdruck dupliziert bzw. gelöscht werden kann – veraltet, daher siehe
_Subform_

|_Rules_ |Erzeugt eine Select-Liste der verfügbaren Aktionen in einer
Komponente. Wird im Kontext der Rechteverwaltung genutzt.

|_Sessionhandler_ |Erzeugt eine Select-Liste der auf dem Webspace
nutzbaren Session-Handler (Datei, Datenbank etc.)

|_Spacer_ |Trenner mit frei wählbarem Text

|_Sql_ |Erzeugt eine Select-Liste aus einer frei definierbaren
SQL-Abfrage

|_Status_ |Generiert eine Select-Liste für die Auswahl des
Veröffentlichungsstatus

|_Subform_ |Ermöglicht es, ein anders JForm-Formular ein- oder mehrfach
in das aktuelle Formular einzubetten. Bei Mehrfacheinbettung ist dabei
das hinzufügen von Duplikaten per Knopfdruck sowie das Sortieren per
Drag&Drop möglich.

|_Tag_ |Bedienelement zur Zuweisung von Tags

|_Tel_ |Erzeugt ein Eingabefeld zur Eingabe einer Telefonnummer

|_Templatestyle_ |Erzeugt eine Select-Liste der installierten
Template-Stile

|_Text_ |Erzeugt ein einzeiliges Feld zur Texteingabe

|_Textarea_ |Erzeugt ein mehrzeiliges Feld zur Texteingabe

|_Timezone_ |Erzeugt eine Select-Liste zur Auswahl einer Zeitzone

|_url_ |Eingabefeld zur Angabe einer URL

|_User_ |Erzeugt eine Select-Liste der vorhandenen Benutzer

|_Usergroup_ |Erzeugt eine Select-Liste der vorhanden Benutzergruppen

|_Useractive_ |Erzeugt eine Select-Liste mit den Freigabe-Werten eines
Nutzers

|_Usergrouplist_ |Siehe _Usergroup_

|_Userstate_ |Erzeugt eine Select-Liste mit den Aktivierungs-Werten
eines Nutzers
|===

==== JLayout (

JLayout dient innerhalb der API zur Trennung von HTML-Markup und
sonstigem Code. Das entsprechende Markup wird dafür in sogenannte
Layouts ausgelagert und die dort anzuzeigenden Daten werden über die
JLayout API übergeben. Dadurch lassen sich außerdem, quasi als
Nebeneffekt, Layouts an mehreren Stellen verwenden und trotzdem zentral
verwalten. In Kapitel 12, „Templates“, haben wir bereits gelernt, dass
JLayout zudem die Nutzung von Overrides unterstützt.

==== Weitere Klassen in der Kurzübersicht

TABELLE 17.8 Weitere wichtige Klassen der Joomla!-API

[width="100%",cols="18%,82%",]
|===
|Klasse |Beschreibung

|JHttp |Führt GET-, POST-, PUT- und DELETE-Abfragen im HTTP-Protokoll
aus und greift dabei automatisch auf die jeweils zur Verfügung stehende
PHP-Funktion (CURL, Socket, Stream) zurück

|JImage |Führt diverse Bildmanipulationsoperationen auf Basis der
GD-Bibliothek durch. Ist durch Filter-Plug-ins erweiterbar.

|JHTML |Erzeugt häufig benötigten HTML-Code für Listen, Formulare,
Menüs, Tabellen, Select-Listen, Tabs und Slider

|JArchive |Unterstützt das Entpacken der Dateiformate _bzip2_, _gzip_,
_tar_ und _zip_

|JAccess |Dient zur Prüfung und Vergabe der Zugriffsrechte des
jeweiligen Benutzers

|JLog |Schreibt Logdateien in wählbaren Formaten und Zielen (Datei,
Datenbank, ­Syslog)

|JMail |Dient zum Versand von E-Mails

|JBrowser |Enthält Informationen zum Browser des jeweiligen Benutzers

|JUser |Erlaubt die Abfrage und Manipulation von Benutzerdaten sowie das
Anlegen neuer Benutzer

|JURI |Erlaubt das Parsen von URLs

|JRoute |Generiert und parst suchmaschinenfreundliche URLs

|JSession |Dient zum Lesen und Schreiben der aktuellen Session-Daten

|JText |Übersetzt Strings mithilfe der installierten Sprachdateien

|JDate |Parst Datumsangaben

|JXMLElement |Dient zum Parsen und Erzeugen von XML-Dokumenten
|===

==== Zur Verfügung stehende Konstanten

Innerhalb der API stehen verschiedene Konstanten zur Verfügung, die zur
Definierung von absoluten Pfadinformationen genutzt werden. Eine
Auflistung der Konstanten finden Sie in Tabelle 17.8.

TABELLE 17.9 Zur Verfügung stehende Konstanten

[width="100%",cols="35%,65%",]
|===
|Konstante |Pfad

|JPATH++_++BASE |Root-Verzeichnis der jeweiligen Applikation
(_/administrator_ im Backend, _/_ im Frontend)

|JPATH++_++ROOT |Root-Verzeichnis der Joomla!-Installation (_/_)

|JPATH++_++SITE |Root-Verzeichnis der Joomla!-Installation (_/_)

|JPATH++_++ADMINISTRATOR |Administratorverzeichnis _/administrator_

|JPATH++_++LIBRARIES |Libraries-Verzeichnis _/libraries_

|JPATH++_++PLUGINS |Plug-ins-Verzeichnis _/plugins_

|JPATH++_++INSTALLATION |Installationsverzeichnis _/installation_

|JPATH++_++THEMES |Template-Verzeichnis _/templates_

|JPATH++_++CACHE |Cache-Verzeichnis _/cache_

|JPATH++_++MANIFESTS |Manifests-Verzeichnis _/manifests_
|===
