=== Das FOF-Framework

Der erste Schritt hin zur Entwicklung Ihrer eigenen Erweiterungen ist
somit gemacht. Sie haben die grundlegenden Strukturen des Frameworks
verstanden und sind in der Lage, eine eigene Komponente für
Stellenanzeigen zu programmieren.

Wenn Sie sich nun tiefer in die Materie einarbeiten und regelmäßig
eigene, auf Joomla! basierende Erweiterungen erstellen, werden Ihnen
vermutlich einige Unzulänglichkeiten der _API_ auffallen, die mit der
Zeit furchtbar nervig werden können. Ein Beispiel gefällig? Wenn Sie ein
neues Joomla!-Erweiterungsprojekt starten, beginnen Sie dann auch damit,
massenhaft Code aus Ihrem letzten Projekt zu kopieren, und ersetzen nur
den Namen der alten durch den Namen der neuen Komponente ? Durch dieses
Vorgehen erzeugen Sie automatisch Code, der stetig wiederholt wird und
gemäß des _DRY_-Konzepts (Don’t repeat yourself) eigentlich nur an einer
Stelle vorhanden sein sollte. In der aktuellen _API_-Version ist dieses
Verhalten zwar weniger ausgeprägt, als es noch zu Zeiten von Joomla! 1.5
war, trotzdem stellt die _Code-Repetition_ derzeit nach wie vor eines
der Hauptprobleme des Joomla!-_Frameworks_ dar.

Ein möglicher Ansatz zur Lösung dieses Problems ist die Verwendung der
Library _Framework-On-Framework_, kurz FOF genannt. FOF ist, wie der
Name bereits vermuten lässt, ein Aufsatz auf dem Joomla-Framework und
dabei als klassisches Rapid-Application-Development-Framework angelegt.
FOF geht davon aus, dass jede Erweiterung im Backend über die
klassischen _BREAD_-Methoden verfügt (Browse, Read, Edit, Add, Delete)
und dass Tabellen- und Spalten- und Dateinamen festgelegten Mustern
folgen. Hält man sich an diese Annahmen, kann man mit FOF z.B.
Backend-Listen- und Formular-Ansichten generieren, für die nur eine
Datenbanktabelle sowie eine XML-basierte View-Datei angelegt werden muss
– den „Rest“, also die passenden Models und Controller sowie das
Rendering des Markups übernimmt FOF vollautomatisch.

FOF ist in Version
2footnote:[https://www.akeebabackup.com/documentation/fof.html] im
Joomla Core integriert und lässt sich dort ohne weitere Vorbereitungen
nutzen, die neuere FOF Version
3footnote:[https://github.com/akeeba/fof/wiki], die über eine Vielzahl
von neuen Funktionen (darunter z.b. Code-Generierungs-Funktionen)
verfügt, muss nachinstalliert werden. Beide Versionen sind
außerordentlich gut dokumentiert und daher insbesondere für „normale“
Erweiterungen defintiv einen Blick wert!

==== Zentrale Konzepte

Um die Vor- und Nachteile des Frameworks zu verstehen, ist es wichtig,
die zentralen Konzepte des Frameworks zu durchschauen.

======= Einsatz von Design Pattern

Der konsequente Einsatz von Design Patterns, also der Anwendung von
bewährten Techniken und Strukturierungsmethoden für den Code, ist eines
der wichtigsten Merkmale von FOF. Die wichtigsten verwendeten Patterns
sind dabei:

*das MVC-Pattern*: Das Framework unterstützt, anders als das
Joomla!-Framework, eine erweiterte MVC-Form, die sich _HMVC_
(Hierarchical MVC) nennt und uns erlaubt, eine zusätzliche Erweiterung
innerhalb der gerade aktiven Erweiterung auszuführen. Durch ein
intelligent programmiertes Standardverhalten des Frameworks wird zur
Abbildung der Standardaktionen BREAD (Browse, Read, Edit, Add, Delete)
kein eigener Code benötigt, wodurch viel Entwicklungszeit eingespart
wird.

*das Observer-Pattern*: ist aus dem Joomla!-Framework bekannt

*das* *Dependency-Injection-Pattern*: dieses, aus vielen modernen
Frameworks bekannte Pattern, basiert auf der Idee, einer Klasse all ihre
externen Abhängigkeiten (Dependencies) als Argumente im Constructor zu
übergeben. Dadurch können Dependencies leichter ausgetauscht werden, was
Flexibilität und bessere Testbarkeit mit sich bringt.

======= Dont Repeat Yourself!

Das DRY-Konzept beschreibt das Bestreben eines guten Entwicklers, seinen
Code nicht ständig zu wiederholen, sondern diesen sich wiederholenden
Code auszulagern und daher wiederverwendbar (reusable) zu machen. Dies
gilt sowohl für einzelne Klassen und Methoden als auch für komplexe
Funktionen wie z.B. eine Kommentarfunktion (Stichwort: HMVC).

======= Convention over Configuration (FOF2)

Das Prinzip Convention over Configuration (Konvention vor Konfiguration)
beschreibt das Bestreben, eine umfangreiche Konfiguration einer
Anwendung dadurch zu vermeiden, dass der Entwickler sich an eine
bestimmte Konvention in der Programmierung hält. Dieses Prinzip, das
auch im Joomla!-Framework weitreichende Anwendung findet, bezieht sich
in erster Linie auf die korrekte Benennung von Ordnern, Dateien, Klassen
und Datenbanktabellen und ermöglicht es beispielsweise, ein bestimmtes
Model in einer View allein dadurch einzubinden, dass das jeweilige Model
korrekt benannt ist.

==== Nachteile des FOF-Frameworks

Das klingt alles in allem nach einer tollen Möglichkeit zur Entwicklung
eigener Webapplikationen und Erweiterungen, oder?

Wie Sie bereits vermutet haben, gibt es auch beim FOF-Projekt einige
Stolpersteine zu beachten, die in die Entscheidungsfindung zur Nutzung
mit einbezogen werden sollten.

*Optimierung auf BREAD-Funktionen*

Beide Versionen des Frameworks sind hochgradig auf die Abwicklung der
BREAD-Funktionen (Browse, Read, Edit, Add, Delete) optimiert und es
bedarf teils sehr viel Anpassungsarbeit, davon abweichende Szenarien zu
realisieren.

*„Magische Funktionen“*

FOF nimmt dem Entwickler viel Arbeit ab, da sehr viele Funktionen auf
quasi magische Art und Weise einfach funktionieren – genau dieser
Umstand, macht die Einarbeitung und das Debugging oftmals mühsam, da man
sich tief in die Libraries von FOF einarbeiten muss, um die Internas zu
verstehen.

*Kleine Community*

Die Community des FOF-Projekts ist derzeit noch relativ klein, was es
schwierig macht, fähige Ansprechpartner für etwaige Probleme zu finden.
Im deutschsprachigen Raum beschränkt sich die Anzahl der Anwender auf
ca. zwei bis drei Dutzend Personen.

==== Vorteile des Frameworks

Durch die konsequente Nutzung von Design Patterns und wichtigen
Technologien gepaart mit sehr sinnvollen Standard-Vorgaben und einer
engagierten Community wird das Framework zur idealen Basis für die
Programmierung von eigenen, komplexen Webanwendungen, die den aktuellen
technischen Standards genügen.

Wenn Sie also eine solche Anwendung planen, lohnt es sich auf jeden
Fall, einen genaueren Blick auf das Framework zu werfen.
