=== Management-Tools

Insbesondere wenn man als Dienstleister im Joomla-Umfeld tätig ist, hat
man es schnell mit einer großen Anzahl an Seiten zutun, die alle
aktualisiert, überwacht und gesichert werden wollen. Die Prüfung „zu
Fuß“, bei der man sich in jedes einzelne Backend einloggen muss, ist
dabei zeitaufwendig und fehleranfällig, weshalb es bereits seit einigen
Jahren eine ganze Reihe Tools gibt, die als zentrale Management-Instanz
für mehrere Seiten fungieren. Zu den bekanntesten dieser Tools zählen
_MyJoomla.com_, _Watchful.li_, _PerfectDashboard_ und _Deevop_, wobei
das Grundprinzip überall ähnlich ist: nach einer Registrierung beim
jeweiligen (kostenpflichtigen) Service lädt man eine kleine
Joomla-_Erweiterung_ im _Backend_ der jeweiligen Installation hoch, die
man mit dem Service verknüpfen möchte.

Über diese Erweiterung hat der jeweilige Service nun vollen Zugriff auf
die jeweilige Installation und kann je nach Service verschiedene
Aktionen wie Updates, Backups, Malware-Checks oder Monitoring-Pings
auslösen. Im Dashboard des jeweiligen Dienstes hat man als Administrator
dabei eine Übersicht über alle Seiten, die dort verwendete
Joomla-Version, die installierten Erweiterungen und den jeweiligen
Status der Seite.

Diese Tools erlauben es selbst große Anzahlen an Joomla-Websites mit
vertretbarem Aufwand zu warten und sind somit elementares Werkzeug für
viele Dienstleister.

[width="99%",cols="14%,86%",options="header",]
|===
|CHV++_++BOX++_++ID++_++02 |
|icn002 |Mit der Installation des jeweiligen Konnektors räumen Sie der
entsprechenden Plattform vollen Zugriff auf die jeweilige Website ein –
wird die entsprechende Plattform also irgendwann einmal erfolgreich
angegriffen, besteht ein hohes Risiko das im Folgenden auch Ihre Website
unter die Kontrolle der Angreifer fällt. Dieser Umstand und
datenschutzrechtliche Aspekte sprechen dafür, dass sie den Einsatz
solcher Tools immer mit dem jeweiligen Seiteninhaber absprechen sollten.
|===

=== Standard-Paket

Wenn wir uns die Vielzahl an Handgriffen, Einstellungen und
Erweiterungen vor Augen führen, die wir in diesem Kapitel und in den
vorherigen Kapiteln getätigt haben, wird schnell klar, dass Sie selbst
als geübter Administrator einigen Minuten brauchen, um eine neue
Installation mit den Standard-Anpassungen zu versehen.

Um sich diese Zeit zu sparen und gleichzeitig die Gefahr von vergessenen
Schritt zu eliminieren, bietet es sich an, die notwendigen Anpassungen
nur ein einziges Mal in einer neutralen Basisinstallation (ohne weitere
Inhalte) vorzunehmen und anschließend ein Akeeba-Backup dieser
Installation zu erstellen. Dieses Backup fungiert dann als
Standard-Paket für den Start neuer Projekte und muss nur hochgeladen und
entpackt werden.
