=== Releasestrategie

Mit der Veröffentlichung von Joomla! 4 im August 2021 hat das Joomla!-Projekt 
eine neue Release-Strategie eingeführt. Diese steht auf zwei Grundsätzen:

* Sematische Versionierung
* Feste Release-Termine

Doch bevor wir zu diesen beiden Teilen der Strategie kommen, noch ein paar 
allgemeine Bemerkungen.

Joomla! benötigt einen Unterbau aus drei Komponenten:

* einen Webserver (meist Apache),
* einen Interpreter für die Skriptsprache PHP und
* eine Datenbank (MySQL, MariaDB oder PostgresQL).

Diese Komponenten (alle genannten stehen ebenso wie Joomla! jeweils unter 
einer Open-Source-Lizenz) entwickeln sich ebenso weiter wie Joomla! Und 
natürlich müssen die eingesetzten Versionen miteinander harmonieren, was 
durch die Releasestrategie von Joomla! sichergestellt werden muss.

==== Sematische Versionierung

Der erste Grundsatz, die sogenannte Semantische Versionierung, gibt
vor, welche Art von Änderung sich auf welche Stelle der Versionsnummer
auswirkt. Eine dreistellige Versionsnummer, also X.Y.Z lässt sich dabei
in die folgenden Komponenten aufteilen:

[arabic]
. X ist die sog. Majorversion. Eine Änderung dieser Ziffer erfolgt, 
wenn das Joomla! Projekt eine Änderung einbaut, die einen
Bruch der Rückwärtskompatiblität zur Folge hat. Mit anderen Worten:
ändert sich die erste Stelle der Versionsnummer, müssen Entwickler ihre
Erweiterungen an die neue Version anpassen, da diese ansonsten nicht
mehr lauffähig sind. Somit ist der Wechsel von der einen zur anderen
Majorversion ein etwas komplexerer Prozess, der im Joomla!-Jargon als
Migration bezeichnet wird und in Kapitel 22 genauer beschrieben ist.
Für jede Hauptversion legt das Joomla! Projekt die Mindestanforderungen 
an den Webserver sowie an PHP und Datenbank fest. Diese Mindestanforderungen
bleiben während der gesamten Lebenszeit der jeweiligen Hauptversion 
unverändert.
. Y ist die sog. Minorversion. Bei einer Änderung der Minorversion
können neue Funktionen zu Joomla! hinzugefügt werden. Ein Update auf 
eine neue Minorversionen ist relativ unkritisch und in der Regel mit 
einem simplen Mausklick durchführbar.
. Z ist die sog. Patchversion. Diese kleinste Art von Update enthält
ausschließlich Fehlerbehebungen (auch als Patches bezeichnet) und kann
ebenfalls bedenkenlos per Mausklick direkt in der Administration von
Joomla! eingespielt werden.

==== Feste Release-Termine

Die Einführung fester Release-Termine ist eine Konsequenz aus den 
Erfahrungen mit der Hauptversion 3 von Joomla! Joomla 3.0.0 erschien 
im August 2012, Joomla 4.0.0 aber erst im August 2021. Da sich ja innerhalb 
einer Hauptversion die Mindestanforderungen nicht ändern dürfen, 
musste z.B. Joomla 3.10.0 im August 2021 noch PHP 5.2 unterstützen, das 
neun Jahre vorher aktuell war. Damit konnten die Joomla-Entwickler die erweiterten 
Möglichkeiten der inzwischen erschienenen PHP-Hauptversionen 7 und 8 
nicht nutzen. Ähnlich sah es bei den Datenbanken aus.

Für Webseitenbetreiber und Entwickler von Erweiterungen schien das eine gute 
Zeit zu sein: Die Webseiten liefen, die Erweiterungen ebenfalls. Warum sollte 
man da viel ändern? Dass sich die Softwarelandschaft in den langen Jahren 
von Joomla 3 gründlich gewandelt hatte, wurde von vielen ignoriert.

Dann kam Joomla 4, und mit ihm der Schock. Joomla hatte neue Mindestanforderungen 
und eine neue Architektur für Erweiterungen. Alte Erweiterungen (einschließlich 
der Templates) funktionierten nicht mehr mit Joomla 4 und PHP 8. Viele 
Updateversuche gingen schief, weil der Migrationsleitfadenfootnote:
[https://docs.joomla.org/Joomla_3.x_to_4.x_Step_by_Step_Migration/de] nicht 
beachtet wurde oder gar nicht bekannt war. Darüber hinaus stellten viele 
Webseitenbetreiber erschrocken fest, dass so manche lieb gewonnene Erweiterung 
nicht mehr weiterentwickelt wurde und für Joomla 4 damit nicht mehr zur 
Verfügung stand.

All dies führte zu großer Verunsicherung bei den Joomla-Anwendern. Als 
Reaktion darauf beschloss das Joomla-Projekt die Einführung von festen 
Release-Zyklen mit folgenden Vorgaben:


+
Alle zwei Jahre erscheint eine neue Majorversion von Joomla. Beginnend 
mit Joomla 5.0.0 ist der Releasetermin immer Mitte Oktober.
+
Nach dem Release einer Hauptversion (N+1) wird die vorhergehende 
Hauptversion (N) noch für zwei weitere Jahre unterstützt, also bis zum 
Release der Hauptversion (N+2).
+
Alle sechs Monate erscheint eine neue Minorversion, also jeweils Mitte 
April und Mitte Oktober. 
+
Innerhalb einer Majorversion (N) ist die Minorversion (N).4 die letzte. Sie 
erscheint gleichzeitig mit der neuen Majorversion (N+1) und bildet die 
Brückenversion von der alten auf die neue Hauptversion. Ein Update auf 
die neue Majorversion (N+1) ist nur von der Minorversion (N).4 möglich. 
Die Minorversion (N).4 erhält nur noch Sicherheitsupdates.
+
Innerhalb einer Minorversion erscheint alle sechs Wochen eine neue 
Patchversion. 
+
In der Release-Ankündigung wird jeweils angegeben, ob es sich um 
ein Sicherheits-kritisches Update handelt.
+
Ab Joomla 5 gibt es für jede Majorversion (N) ein sogenanntes 
"Kompatibilitäts-Plugin". Ist dieses Plugin aktiviert, laufen alle 
Erweiterungen (inkl. Templates), die in der Majorversion (N-1) lauffähig 
waren, auch in der Majorversion (N).
