=== Releasestrategie

Mit der Veröffentlichung von Joomla! 4 im August 2021 hat das Joomla!-Projekt 
eine neue Release-Strategie eingeführt. Diese steht auf zwei Grundsätzen:
* Sematische Versionierung
* Feste Release-Termine

Doch bevor wir zu diesen beiden Teilen der Strategie kommen, noch ein paar 
allgemeine Bemerkungen.

Joomla! benötigt einen Unterbau aus drei Komponenten:
* einen Webserver (meist Apache),
* einen Interpreter für die Skriptsprache PHP und
* eine Datenbank (MySQL, MariaDB oder PostgresQL).

Diese Komponenten (alle genannten stehen ebenso wie Joomla! jeweils unter 
einer Open-Source-Lizenz) entwickeln sich ebenso weiter wie Joomla! Und 
natürlich müssen die eingesetzten Versionen miteinander harmonieren, was 
durch die Releasestrategie von Joomla! sichergestellt werden muss.

==== Sematische Versionierung

Der erste Grundsatz, die sogenannte Semantische Versionierung, gibt
vor, welche Art von Änderung sich auf welche Stelle der Versionsnummer
auswirkt. Eine dreistellige Versionsnummer, also X.Y.Z lässt sich dabei
in die folgenden Komponenten aufteilen:

[arabic]
. X ist die sog. Majorversion. Eine Änderung dieser Ziffer erfolgt, 
wenn das Joomla! Projekt eine Änderung einbaut, die einen
Bruch der Rückwärtskompatiblität zur Folge hat. Mit anderen Worten:
ändert sich die erste Stelle der Versionsnummer, müssen Entwickler ihre
Erweiterungen an die neue Version anpassen, da diese ansonsten nicht
mehr lauffähig ist. Somit ist der Wechsel von der einen zur anderen
Majorversion ein etwas komplexerer Prozess, der im Joomla!-Jargon als
Migration bezeichnet wird und in Kapitel 22 genauer beschrieben ist.
Für jede Hauptversion legt das Joomla! Projekt die Mindestanforderungen 
an den Webserver sowie an PHP und Datenbank fest. Diese Mindestanforderungen
bleiben während der gesamten Lebenszeit der jeweiligen Hauptversion 
unverändert.
. Y ist die sog. Minorversion. Bei einer Änderung der Minorversion
können neue Funktionen zu Joomla! hinzugefügt werden. Ein Update auf 
eine neue Minorversionen ist relativ unkritisch und in der Regel mit 
einem simplen Mausklick durchführbar.
. Z ist die sog. Patchversion. Diese kleinste Art von Update enthält
ausschließlich Fehlerbehebungen (auch als Patches bezeichnet) und kann
ebenfalls bedenkenlos per Mausklick direkt in der Administration von
Joomla! eingespielt werden.

==== Feste Release-Termine

Die Einführung fester Release-Termine ist eine Konsequenz aus den 
Erfahrungen mit der Hauptversion 3 von Joomla! Joomla 3.0.0 erschien 
im August 2012, Joomla 4.0.0 aber erst im August 2021. Da sich ja innerhalb 
einer Hauptversion die Mindestanforderungen nicht ändern dürfen, 
musste z.B. Joomla 3.10.0 im August 2021 noch PHP 5.2 unterstützen, das 
2012 aktuell war. Damit konnten die Joomla-Entwickler die erweiterten 
Möglichkeiten der inzwischen erschienen PHP-Hauptversionen 7 und 8 
nicht nutzen. Ähnlich sah es bei den Datenbanken aus.





+
Um den Nutzern von Joomla! eine gewisse langfristige Planungssicherheit
zu geben, gibt das Joomla!-Projekt feste Mindestzeiträume an, in denen
eine bestimmte Version noch mit Sicherheitsupdates und Fehlerbehebungen
versorgt wird. Grundregel ist dabei, dass die jeweils letzte
Minorversion eines Major-Zweigs für 2 Jahre unterstützt wird.
+
Ein kleines Beispiel, um diesen etwas abstrakten Satz mit konkreten
Inhalten zu füllen:
+
Wir nehmen einmal an, dass am 01.01.2018 eine fiktive Joomla!-Version
4.0 erscheint. Im weiteren Entwicklungsverlauf erscheinen für diesen
neuen Versionszweig 4.x nun mehrere Minor-Releases, die neue Funktionen
nachrüsten. Die letzte Minor-Version, in unserem fiktiven Fall wäre das
zum Beispiel 4.9.0, erscheint dabei am 01.03.2020. Der Releasetermin
dieser letzten Minor-Version wäre nun ausschlaggebend für das Ende des
Supportzeitraums von 2 Jahren, womit der Support für die Joomla!-Version
4.x am 28.02.2022 enden würde. Im Rahmen dieses Supportzeitraums würde
es weiterhin Fehlerbehebungen und Sicherheitsupdates geben, die sich
dann auf die letzte Ziffer der Versionsnummer (z.B. als 4.9.1, 4.9.2
etc.) auswirken würden.
+
Joomla! bietet Entwicklern und Nutzern hier also eine langfristige
Planungssicherheit und eignet sich daher perfekt für Projekte, die über
einen längeren Zeitraum unterstützt werden müssen.
